version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/hello-world
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  AllowTraffic:
    - location: .
      timeout: 300
